{{- if .Values.nexusBackup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.fullname" . }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
type: Opaque
data:
  nexus.nexusAdminPassword: {{ printf "Basic %s" (printf "admin:%s" .Values.nexusBackup.nexusAdminPassword | b64enc) | b64enc | quote }}
{{- end }}
